name: Make hackpack after merging to main
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref}}
          token: ${{ secrets.SACHIN_PAT }}
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra
      - run: make veryclean && make hackpack
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add hackpack.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Build artifacts [skip ci]' && git push)
  